#!/usr/bin/env bash
# Display all running processes with USER, STARTED time, and CMD
ps -eo user,lstart,cmd --sort=start_time | awk 'NR==1 {print "USER STARTED CMD"; next} {printf "%s %s %s %s %s %s %s\n", $1, $2, $3, $4, $5, $6, substr($0, index($0,$8))}'
