#!/usr/bin/env bash
# This script runs an infinite loop and handles the SIGTERM signal gracefully
# Define a trap to handle SIGTERM
trap 'echo "I am invincible!!!"' SIGTERM
# Infinite loop
while true
do
    echo "To infinity and beyond"
    sleep 2
done
